### ISSUE TITLE
Eventually remove the deprecated "oldmozscripts"

### ISSUE THREAD

**Issue by ilikenwf** [nightingale-media-player/nightingale-deps#1]
After we find a way around using the contents of "oldmozscripts" in the tree's root, we need to remove them from this repo.

**Comment by ilikenwf** [comment]
Depends on the following:

https://github.com/nightingale-media-player/nightingale-hacking/issues/126

**Comment by johnmurrayvi** [comment]
Closing, fixed with any new dep build. Already in 9.0.1 as well.
