### ISSUE TITLE
Remove nsis

### ISSUE THREAD

**Issue by rsjtdrjgfuzkfg** [nightingale-media-player/nightingale-deps#13]
@GeekShadow why didn't you do that when updating to inno?

**Comment by rsjtdrjgfuzkfg** [comment]
See also https://github.com/nightingale-media-player/nightingale-hacking/commit/0342f294699459c185fa631b47bfb95e6d298aa1

**Comment by ilikenwf** [comment]
Isn't this fixed?

**Comment by rsjtdrjgfuzkfg** [comment]
Jup, with the last dep update... did not see this one ;)
