### ISSUE TITLE
Is the Mozilla gst plugin needed?

### ISSUE THREAD

**Issue by freaktechnik** [nightingale-media-player/nightingale-deps#16]
While looking through the failing unittests I noticed, that we are missing a gst plugin containing "mozilla". A little research led me to [this](https://github.com/nightingale-media-player/nightingale-deps/tree/c105f3f895f31f50be1c85d40cd7b62574cf7752/gst-plugins-bad/ext/mozilla). It seems that it exposes a gst pipe as XPCOM output stream?
If it enhances our functionality, we should have it in our ppa and depend on it and ship it with all other ngale versions.

**Comment by johnmurrayvi** [comment]
Hmm.... For Linux, the Gstreamer stuff isn't built at all. I wonder if gst-plugins-bad generally includes the Mozilla plugin when it's distributed.

**Comment by mook** [comment]
The Mozilla gst plugin is Songbird/Nightingale specific. It's basically
used to pull data from the Mozilla network stack, so you get things like
correct cookies, IIRC. Pretty sure not having it would be a bad idea.

**Comment by freaktechnik** [comment]
Well, our linux builds already live without it. So we need to restore it for linux and start bundling it with linux builds and optimally make it a dependency in the Ubuntu PPA.

**Comment by johnmurrayvi** [comment]
With the newer xul branch moving to gstreamer-1.0 and having it be bundled with all of the builds, are there any other gstreamer packages/plugins that should be looked at?

**Comment by johnmurrayvi** [comment]
Can this be closed now since it's in the nightingale-hacking tree? Or do you want to keep it open and have it be part of the deps on newer xulrunner versions?

**Comment by freaktechnik** [comment]
I think we can close this here, as we build gstmozilla with nightingale now.
