### ISSUE TITLE
GNU/Linux: Issues with xulrunner binaries

### ISSUE THREAD

**Issue by darealshinji** [nightingale-media-player/nightingale-deps#18]
When I open a Debian package I get Lintian error messages about embedded libraries in some binaries and warnings about hardening-no-relro. Furthermore when I build Nightingale on Launchpad I get some warnings about "useless dependencies" in the build log.

Well, first of all the embedded libraries:
E: nightingale: embedded-library usr/lib/nightingale/components/sbDBEngine.so: sqlite
E: nightingale: embedded-library usr/lib/nightingale/xulrunner/libsqlite3.so: sqlite
E: nightingale: embedded-library usr/lib/nightingale/xulrunner/libxul.so: zlib
E: nightingale: embedded-library usr/lib/nightingale/xulrunner/libxul.so: libjpeg
E: nightingale: embedded-library usr/lib/nightingale/xulrunner/libxul.so: libtheora
E: nightingale: embedded-library usr/lib/nightingale/xulrunner/updater: bzip2

Usually it's better to avoid it, at least for stuff like compression libraries which are installed by default on any GNU system. I did take a look at it, you can set the config files in /nightingale-deps-xul-192-new/xulrunner-1.9.2/mozconfigs/ to use the system's libraries instead of embedded ones. So unless there's a reason to embed some libraries, like compatibility issues, I recommend to link the binaries against the system's shared libraries.

Now hardening-no-relro which is quite a long list:
W: nightingale: hardening-no-relro usr/lib/nightingale/nightingale-bin
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/components/libimgicon.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/js
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libfreebl3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libmozjs.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libnspr4.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libnss3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libnssckbi.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libnssdbm3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libnssutil3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libplc4.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libplds4.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libsmime3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libsoftokn3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libsqlite3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libssl3.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libxpcom.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/libxul.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/mangle
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/mozilla-xremote-client
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/nsinstall
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/plugin-container
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/plugins/libnullplugin.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/plugins/libunixprintplugin.so
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/regxpcom
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/shlibsign
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/updater
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/xpcshell
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/xpidl
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/xpt_dump
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/xpt_link
W: nightingale: hardening-no-relro usr/lib/nightingale/xulrunner/xulrunner-bin

"This package provides an ELF binary that lacks the "read-only relocation" link flag." - http://lintian.debian.org/tags/hardening-no-relro.html
So, I assume there's something missing in one of the makefiles? I'm not an expert so I can't really tell you what this caused and how to fix it, but I wanted to let you know about it.

Those are the warnings from dpkg-shlibdeps in the Debian package build log from Launchpad:

amd64:
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/libxul.so debian/nightingale/usr/lib/nightingale/xulrunner/xulrunner-bin were not linked against libXext.so.6 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/libxul.so debian/nightingale/usr/lib/nightingale/xulrunner/xulrunner-bin debian/nightingale/usr/lib/nightingale/xulrunner/components/libimgicon.so debian/nightingale/usr/lib/nightingale/xulrunner/updater debian/nightingale/usr/lib/nightingale/xulrunner/plugins/libnullplugin.so were not linked against libpangocairo-1.0.so.0 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/libxul.so debian/nightingale/usr/lib/nightingale/xulrunner/xulrunner-bin debian/nightingale/usr/lib/nightingale/xulrunner/components/libimgicon.so debian/nightingale/usr/lib/nightingale/xulrunner/updater debian/nightingale/usr/lib/nightingale/xulrunner/plugins/libnullplugin.so were not linked against libgio-2.0.so.0 (they use none of the library's symbols)
https://launchpad.net/~djcj/+archive/test-deletedppa23/+build/5659638/+files/buildlog_ubuntu-saucy-amd64.nightingale_1.12.2a%2B20140303-1%7Esaucy2%7Eppa2_UPLOADING.txt.gz

i386:
/xulrunner-bin were not linked against libXext.so.6 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/libxul.so debian/nightingale/usr/lib/nightingale/xulrunner/xulrunner-bin debian/nightingale/usr/lib/nightingale/xulrunner/components/libimgicon.so debian/nightingale/usr/lib/nightingale/xulrunner/updater debian/nightingale/usr/lib/nightingale/xulrunner/plugins/libnullplugin.so were not linked against libpangocairo-1.0.so.0 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/components/libmozgnome.so debian/nightingale/usr/lib/nightingale/xulrunner/libxul.so debian/nightingale/usr/lib/nightingale/xulrunner/xulrunner-bin debian/nightingale/usr/lib/nightingale/xulrunner/components/libimgicon.so debian/nightingale/usr/lib/nightingale/xulrunner/updater debian/nightingale/usr/lib/nightingale/xulrunner/plugins/libnullplugin.so were not linked against libgio-2.0.so.0 (they use none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/nightingale/usr/lib/nightingale/xulrunner/components/libmozgnome.so debian/nightingale/usr/lib/nightingale/xulrunner/components/libnkgnomevfs.so were not linked against libgmodule-2.0.so.0 (they use none of the library's symbols)
https://launchpad.net/~djcj/+archive/test-deletedppa23/+build/5659639/+files/buildlog_ubuntu-saucy-i386.nightingale_1.12.2a%2B20140303-1%7Esaucy2%7Eppa2_UPLOADING.txt.gz

If those are really useless dependencies it'd be of course better to avoid them. I tried to remove the mentioned libraries from the dynamic section with patchelf, repacked the xulrunner archive and built a new Debian package using that, but the issue remained, so if this is really an issue it has to be fixed at compile time.

**Comment by freaktechnik** [comment]
I do know for a fact that we had problems with sqlite on Debian systems in the past - even with the current configuration. Maybe because we relink some of the binaries against libsqlite3 of the system.
Edit: I do no get the norelro warnings on my system.

**Comment by darealshinji** [comment]
I was curious how many useless dependencies this package really had. So I added some lines to debian/rules which removed all those useless deps from the ELF headers (very hacky, I don't recommend that).  In the end libxext6 and libpangocairo-1.0-0 were the only packages that didn't need to be installed. The rest is still in use by other parts of the program. The installed size of those two libs sum up to less then a half MB. I thought it would be more.

Here's the debian/rules file I used: https://gist.github.com/darealshinji/132b76a161b90e791c7a

**Comment by johnmurrayvi** [comment]
@darealshinji I built some deps last night for someone on IRC that _should_ have hardening. If you'd like to check them as well, here are the links:
[linux-x86_64-hardening.tar.bz2.md5](http://sourceforge.net/projects/ngale/files/testing-builds/linux-x86_64-hardening.tar.bz2.md5/download)
[linux-x86_64-hardening.tar.bz2](http://sourceforge.net/projects/ngale/files/testing-builds/linux-x86_64-hardening.tar.bz2/download)

Thanks for all of your help with this!

**Comment by darealshinji** [comment]
No hardenings at all ;-)
But many rpaths and still embedded libs in libxul.so, updater and sbDBEngine.so:
http://tny.cz/cd20cf43
The rpaths can be deleted with chrpath (or deactivated at compile time?).
These could be overridden ~~or replaced with system-libs~~ (doesn't work with the system libs, so instead override them for Launchpad releases):
embedded-library libsqlite3.so: sqlite
embedded-library libnss3.so: nss

~~Oh, and there are no more files with executable bit which aren't supposed to. I deactivated the chmod routine in the Makefile to check that.~~
I thought I deactivated it, but I didn't. There are still unusual permissions set.

edit:
I just checked the Ubuntu Firefox package and they override some of their warnings:
embedded-library libxul.so: libjpeg
embedded-library libmozsqlite3.so: sqlite
image-file-in-usr-lib

**Comment by darealshinji** [comment]
I took the time and fixed the permissions, removed the rpaths and did some other stuff (full explanation in changes file): http://www.sendspace.com/file/kj7p1s

**Comment by johnmurrayvi** [comment]
Awesome! Thank you so much for helping with this. I'm currently trying to solve some windows issues, but as soon as I get a chance to, I'll boot back into Linux and check it out.

**Comment by johnmurrayvi** [comment]
I think I got the permissions fixed (in the other issue), so would the rpaths be the only remaining fixes needed?

**Comment by darealshinji** [comment]
I think so. If you can't find a way to deactivate rpaths at compile time, you can delete them afterwards with chrpath.

**Comment by johnmurrayvi** [comment]
So I think the rpaths are because I have an arm toolchain in my PATH... because those rpaths match exactly to the location of it in my system. Going to take it out of my PATH and rebuild. Hopefully that fixes it.

**Comment by johnmurrayvi** [comment]
Yep... that was it... I have no idea why it was setting the rpaths lol.

**Comment by johnmurrayvi** [comment]
@darealshinji Here's a fresh build:
[linux-x86_64-lintian-20140718.tar.bz2](http://sourceforge.net/projects/ngale/files/testing-builds/linux-x86_64-lintian-20140718.tar.bz2/download)
[linux-x86_64-lintian-20140718.tar.bz2.md5](http://sourceforge.net/projects/ngale/files/testing-builds/linux-x86_64-lintian-20140718.tar.bz2.md5/download)

**Comment by darealshinji** [comment]
Looks fine to me.

**Comment by freaktechnik** [comment]
I've started trying to build the deps using the lint script (to later build the deps for the release package automatically). After figuring out some of the missing deps I ran into

```
In file included from /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxPangoFonts.cpp:64:0:
../../../dist/system_wrappers/tttables.h:3:27: fatal error: tttables.h: No such file or directory
compilation terminated.
gfxPlatformGtk.cpp
c++ -o gfxPlatformGtk.o -c -I../../../dist/system_wrappers -include /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/config/gcc_hidden.h -DIMPL_THEBES -DWOFF_MOZILLA_CLIENT -DMOZILLA_INTERNAL_API -D_IMPL_NS_COM -DEXPORT_XPT_API -DEXPORT_XPTC_API -D_IMPL_NS_COM_OBSOLETE -D_IMPL_NS_GFX -D_IMPL_NS_WIDGET -DIMPL_XREAPI -DIMPL_NS_NET -DIMPL_THEBES  -DZLIB_INTERNAL -DOSTYPE=\"Linux3.13\" -DOSARCH=Linux  -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src -I. -I../../../dist/include -I../../../dist/include/nsprpub  -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/nspr -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/nss         -fPIC  -D_FORTIFY_SOURCE=2  -fno-rtti -fno-exceptions -Wall -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-invalid-offsetof -Wno-long-long -pedantic -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fshort-wchar -pthread -pipe  -DDEBUG -D_DEBUG -DDEBUG_martin -DTRACING -fno-inline -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/cairo -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gtk-unix-print-2.0   -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -D_FORTIFY_SOURCE=2  -DMOZILLA_CLIENT -include ../../../mozilla-config.h -Wp,-MD,.deps/gfxPlatformGtk.pp /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxPlatformGtk.cpp
gfxGdkNativeRenderer.cpp
c++ -o gfxGdkNativeRenderer.o -c -I../../../dist/system_wrappers -include /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/config/gcc_hidden.h -DIMPL_THEBES -DWOFF_MOZILLA_CLIENT -DMOZILLA_INTERNAL_API -D_IMPL_NS_COM -DEXPORT_XPT_API -DEXPORT_XPTC_API -D_IMPL_NS_COM_OBSOLETE -D_IMPL_NS_GFX -D_IMPL_NS_WIDGET -DIMPL_XREAPI -DIMPL_NS_NET -DIMPL_THEBES  -DZLIB_INTERNAL -DOSTYPE=\"Linux3.13\" -DOSARCH=Linux  -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src -I. -I../../../dist/include -I../../../dist/include/nsprpub  -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/nspr -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/nss         -fPIC  -D_FORTIFY_SOURCE=2  -fno-rtti -fno-exceptions -Wall -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-invalid-offsetof -Wno-long-long -pedantic -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -fshort-wchar -pthread -pipe  -DDEBUG -D_DEBUG -DDEBUG_martin -DTRACING -fno-inline -I/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/dist/include/cairo -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gtk-unix-print-2.0   -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -D_FORTIFY_SOURCE=2  -DMOZILLA_CLIENT -include ../../../mozilla-config.h -Wp,-MD,.deps/gfxGdkNativeRenderer.pp /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxGdkNativeRenderer.cpp
make[7]: *** [gfxPangoFonts.o] Error 1
make[7]: *** Waiting for unfinished jobs....
In file included from ../../../dist/include/gfxFont.h:48:0,
                 from ../../../dist/include/gfxPangoFonts.h:44,
                 from /home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxPlatformGtk.cpp:50:
../../../dist/include/gfxFontUtils.h: In member function ‘void gfxFontInfoLoader::StartLoader(PRUint32, PRUint32)’:
../../../dist/include/gfxFontUtils.h:632:18: warning: variable ‘timerInterval’ set but not used [-Wunused-but-set-variable]
/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxPlatformGtk.cpp: In member function ‘virtual already_AddRefed<gfxASurface> gfxPlatformGtk::CreateOffscreenSurface(const gfxIntSize&, gfxASurface::gfxImageFormat)’:
/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/gfx/thebes/src/gfxPlatformGtk.cpp:174:9: warning: variable ‘glitzf’ set but not used [-Wunused-but-set-variable]
make[7]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/gfx/thebes/src'
make[6]: *** [libs] Error 2
make[6]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/gfx/thebes'
make[5]: *** [libs] Error 2
make[5]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug/gfx'
make[4]: *** [libs_tier_gecko] Error 2
make[4]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug'
make[3]: *** [tier_gecko] Error 2
make[3]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla/compiled/xulrunner-debug'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2/mozilla'
make: *** [xr-build-debug] Error 2
make: Leaving directory `/home/martin/dev/ngale/nightingale-deps/xulrunner-1.9.2'
```

I would assume this is a bit of a mess thanks to -j4?

EDIT: changing the include from tttables.h to freetype/tttables.h fixed it.

**Comment by johnmurrayvi** [comment]
@darealshinji, Awesome, thanks again for all of your help!

@freaktechnik  Ahh, looks like you've got the old (<2.5) freetype version. I think the fix you mentioned in the edit was the only include that got changed, so I think everything else should build without issue.
