### ISSUE TITLE
Xul 9.X - Set all .py scripts to executable, remove useless junk from builds

### ISSUE THREAD

**Issue by ilikenwf** [nightingale-media-player/nightingale-deps#2]
With xulrunner version 9, I find that empty directories are in the final build, and that .py files aren't executable...

**Comment by ilikenwf** [comment]
See the working/in progress branch for xul v9+ :
https://github.com/nightingale-media-player/nightingale-deps/tree/xul-v9.0.1

**Comment by johnmurrayvi** [comment]
I think this is fixed in:
https://github.com/nightingale-media-player/nightingale-deps/tree/xul-9.0.1

So I'm going to close this and if it happens again, we can reopen it.
