### ISSUE TITLE
Ubuntu 14.04 i386 build via lint-build.sh fails

### ISSUE THREAD

**Issue by darealshinji** [nightingale-media-player/nightingale-deps#20]
I want to build the deps on Launchpad and create a separate devel package for it which I can use to build NG. The i386 build for Ubuntu 14.04 fails, and I'm unsure why. It builds on 12.04 for that architecture.

Build log: https://launchpadlibrarian.net/180526600/buildlog_ubuntu-trusty-i386.nightingale-deps_20140722-1~trusty0.4_FAILEDTOBUILD.txt.gz
Repository: https://launchpad.net/~djcj/+archive/ubuntu/testing/+packages

**Comment by freaktechnik** [comment]
Yup. https://code.launchpad.net/~nightingaleteam/+recipe/nightingale-lint-nightly

Interesting that it fails on 14.04 but not on 12.04.

**Comment by darealshinji** [comment]
On 12.04 the package 'g++' installs 'g++-4.6', on 14.04 it installs 'g++-4.8'. Might have something to do with it?

**Comment by johnmurrayvi** [comment]
I downloaded a i386 copy of 14.04 a little bit ago and I was going to try to look at it if I have a chance. 

@darealshinji That could be an issue actually...

**Comment by darealshinji** [comment]
Adding 'g++-4.6' to the build dependencies and applying this patch seems to fix the issue:

``` diff
--- a/xulrunner-1.9.2/mozconfigs/xulrunner.linux.debug.i686.lintian.mozconfig
+++ b/xulrunner-1.9.2/mozconfigs/xulrunner.linux.debug.i686.lintian.mozconfig
@@ -7,6 +7,8 @@
 mk_add_options BUILD_OFFICIAL=1
 mk_add_options MOZILLA_OFFICIAL=1

+export CXX=g++-4.6
+
 # hardening flags
 export CFLAGS="-fstack-protector --param=ssp-buffer-size=4"
 export CPPFLAGS="-D_FORTIFY_SOURCE=2"
--- a/xulrunner-1.9.2/mozconfigs/xulrunner.linux.release.i686.lintian.mozconfig
+++ b/xulrunner-1.9.2/mozconfigs/xulrunner.linux.release.i686.lintian.mozconfig
@@ -7,6 +7,8 @@
 mk_add_options BUILD_OFFICIAL=1
 mk_add_options MOZILLA_OFFICIAL=1

+export CXX=g++-4.6
+
 # hardening flags
 export CFLAGS="-fstack-protector --param=ssp-buffer-size=4"
 export CPPFLAGS="-D_FORTIFY_SOURCE=2"
```
