### ISSUE TITLE
Windows Build Issues (nothing works)

### ISSUE THREAD

**Issue by ilikenwf** [nightingale-media-player/nightingale-deps#3]
On the xul-192-new branch:

Build output from @rsjtdrjgfuzkfg : http://pastebin.mozilla.org/1846236

Seems to me that it's not liking his MSVC compiler. On top of that he speculates that the wrapper scripts are confusing CC and CXX. There may also be some issues with file paths between Unix path types and windwows path type conversion going on.

He also thinks cmake may be breaking as well. Suggestions?

@mook

**Comment by ilikenwf** [comment]
@rsjtdrjgfuzkfg  - have you tried rebuilding these in a while? Do a git pull and give it a try...

I think I've figured out the order for building if the Makefile isn't working properly.

**Comment by rsjtdrjgfuzkfg** [comment]
Doesn't work for me, cmake tries a self-check which fails. http://pastebin.mozilla.org/2025782

**Comment by ilikenwf** [comment]
I'm not all that familiar with cmake...

@Mook - any chance you can tell what's going on here?

**Comment by johnmurrayvi** [comment]
I've got xul-192-new compiling on win, so I'm gonna close this.
