### ISSUE TITLE
Break Buildsystem up Into Pieces...

### ISSUE THREAD

**Issue by ilikenwf** [nightingale-media-player/nightingale-deps#8]
Perhaps follow a model similar to how android breaks things up and uses repo to pull the appropriate files down?

For Linux, this will be completely unnecessary here in a release or two down the line, but for Mac and Windows, it'll always be necessary.

**Comment by rsjtdrjgfuzkfg** [comment]
So we'd need to spam out github organization with new repos for each dep? But I agree that we should make this more slim...

**Comment by ilikenwf** [comment]
Well, we could just have the Makefile and a subrepo and pull from the project's source repos a specific tag/milestone...and not keep things locally.

We shouldn't need to patch anything once we get past xul15+ and get vanilla sqlite working.
